/**
 * Express.js Server with support of TS
 */
import fs from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath, pathToFileURL } from 'node:url'
import dotenv from 'dotenv'
import express from 'express'
import type { ViteDevServer } from 'vite'
import defConstants from './lib/constant' // no aliases can be used if the launcher is build using tsc.
import { loadDefConf } from './lib/utils'

// path utilities
const __dirname: string = path.dirname(fileURLToPath(import.meta.url))
const __root: string = process.cwd()
const resolve = (inBase: string, inPath: string) => path.resolve(inBase, inPath)
const resolveToURL = (inBase: string, inPath: string) =>
    pathToFileURL(resolve(inBase, inPath))

// load the file containing default configurations
const defConfigs = await loadDefConf(
    resolveToURL(__root, defConstants.confFile)
)

// Constants
dotenv.config()
const isProduction = process.env['NODE_ENV'] === 'production'
const webHost =
    process.env['VITE_WEB_HOST'] || (defConfigs['webHost'] as string)
const webPort = parseInt(
    process.env['VITE_WEB_PORT'] || (defConfigs['webPort'] as string),
    10
)
const base = process.env['VITE_BASE'] || (defConfigs['webBase'] as string)

// Cached production assets
const templateHtml = isProduction
    ? await fs.readFile(
          resolveToURL(
              __dirname,
              path.join(
                  defConstants.clientBuildPath,
                  defConstants.entryHtmlFile
              )
          ),
          'utf-8'
      )
    : ''

// Create http server
const app = express()

// Add Vite or respective production middlewares
let vite: ViteDevServer
if (!isProduction) {
    const { createServer } = await import('vite')
    vite = await createServer({
        server: { middlewareMode: true },
        appType: 'custom',
        base,
    })
    app.use(vite.middlewares)
} else {
    const clientRootFolder = resolveToURL(
        __dirname,
        defConstants.clientBuildPath
    ).pathname

    const compression = (await import('compression')).default
    const sirv = (await import('sirv')).default
    app.use(compression())
    app.use(base, sirv(clientRootFolder, { extensions: [] }))
}

// API endpoint
app.get('/end-point', async (req, res) => {
    res.json({
        message: 'Data generated by API',
        timeStamp: new Date().getTime(),
    })
})

// Serve HTML
app.use('*all', async (req, res) => {
    try {
        const url = req.originalUrl.replace(base, '')

        let template: string
        let render: (x: string) => { head: string; html: string }
        if (!isProduction) {
            const entryServerPoint = resolveToURL(
                __root,
                path.join('src', defConstants.entryServerScript + '.ts')
            )
            // Always read fresh template in development
            template = await fs.readFile(defConstants.entryHtmlFile, 'utf-8')
            template = await vite.transformIndexHtml(url, template)
            render = (await vite.ssrLoadModule(entryServerPoint.pathname))[
                'render'
            ]
        } else {
            template = templateHtml

            const entryServerPoint = resolveToURL(
                __dirname,
                path.join(
                    defConstants.serverBuildPath,
                    defConstants.entryServerScript + '.js'
                )
            )

            // eslint-disable-next-line @typescript-eslint/ban-ts-comment
            // @ts-expect-error
            render = (await import(entryServerPoint))['render']
        }

        const rendered = await render(url)

        const html = template
            .replace(`<!--app-head-->`, rendered.head ?? '')
            .replace(`<!--app-html-->`, rendered.html ?? '')

        res.status(200).set({ 'Content-Type': 'text/html' }).send(html)
    } catch (e) {
        if (e instanceof Error) {
            if (!isProduction) {
                vite?.ssrFixStacktrace(e)
                console.log(e.stack)
                res.status(500).end(e.stack)
            } else {
                res.status(500).end(e.message)
            }
        } else {
            console.log(e)
            res.status(500).end('Unknown error')
        }
    }
})

// Start http server
app.listen(webPort, webHost, () => {
    console.log(`Server started at http://${webHost}:${webPort}`)
})
