import { expect, test } from '@playwright/test'

test('test', async ({ page }) => {
    await page.goto('/')
    await expect(
        page.getByRole('heading', { name: 'Vite Build Tool' })
    ).toBeVisible()
    await page.getByText('Hello JSX! ☄️').click()
    await expect(page.locator('#counter')).toContainText('count is 0')
    await page.getByRole('button', { name: 'count is' }).click()
    await expect(page.locator('#counter')).toContainText('count is 1')
    await page.getByRole('button', { name: 'Fetch data' }).click()
    await expect(page.getByRole('listitem')).toContainText(
        'Data generated by API'
    )
})
